### ISSUE TITLE
RSS Club posts don't appear in RSS Feed (anymore)

### ISSUE THREAD

**Issue by cybeardjm** [pfefferle/wordpress-rss-club#1]
Just published 2 new RSS Club posts on my main blog, they don't appear in the RSS feed, but do appear in the XML sitemap.
On 2nd blog, no problem, RSS Club posts appear in feed.

What/where should I check? Can I safely disable/enable the RSS Club plugin, in case some option went "rogue"...?

**Comment by pfefferle** [comment]
🤔

The plugin does not delete anything, so it should be fine to disable/enable it!

**Comment by cybeardjm** [comment]
OK, did deactivate/reactivate (have no caching plugin), same...
In Troubleshoot mode, it's fine, so there's a conflict with another plugin.
Will compare with the blog where it works fine (don't have many differences, so should be quick...)

**Comment by cybeardjm** [comment]
OK, found it, it's a conflict with IndieBlocks by @janboddez
In Post Types, after enabling Notes and/or Likes, if "Include in main feed" is activated, the RSS Club posts disappear from the Feed.
If disabled, they reappear.
Indeed, I use Notes & Likes on the main blog, and both where included in the main feed. I don't use these on my  second blog.

**Comment by janboddez** [comment]
I think this is the cause of the issue: https://github.com/pfefferle/wordpress-rss-club/blob/8b3d0caa99a46ee03597254e689fe603dc554f97/rss-club.php#L88

The `rssclub` post type is added to the main feed only if the `post_type` query var is not set. But IndieBlocks (when that option is enabled) does set a `post_type` query var. Just like this plugin! In order to add the post types! :-)

**Comment by janboddez** [comment]
IndieBlocks does almost the same. Because the only way to tell a feed is the _main_ feed, is ... by checking `post_type` isn't set: https://github.com/janboddez/indieblocks/blob/main/includes/class-feeds.php#L72-L83

Because IndieBlocks' callback has a prio of 9, it will run before this plugin's. And `rssclub` posts won't get included ...

Not sure how to solve this (other than a custom filter to let developers add more post types). Or a different way of checking for the main feed ...

I personally use a _category_ for "RSS-only posts." :-D

**Comment by janboddez** [comment]
> Not sure how to solve this (other than a custom filter to let developers add more post types).

Or you could just do (even now), e.g., in your theme or so:
```
add_filter( 'request', function ( $query_vars ) {
	if ( isset( $query_vars['feed'] ) && ! isset( $query_vars['post_type'] ) ) {
		$query_vars['post_type'] = array( 'post', 'rssclub', 'indieblocks_note', 'indieblocks_like' );
	}

	return $query_vars;
}, 8 ); // Must be lower than 9!
```
That should solve your problem.

I could probably also include the `rssclub` type in a next version of IndieBlocks. Not the definition, I mean, but make sure that _if_ it exists, it is included in the main feed.

**Comment by pfefferle** [comment]
thanks for debugging that @janboddez !!!

what about

```PHP
/**
 * Add custom post type to main query
 *
 * @param array $query_vars The query vars.
 *
 * @return array The modified query vars.
 */
function request( $query_vars ) {
	if ( isset( $query_vars['feed'] ) ) {
		if ( ! isset( $query_vars['post_type'] ) ) {
			$query_vars['post_type'] = array( 'post' );
		}

		$query_vars['post_type'][] = 'rssclub';
	}

	return $query_vars;
}
add_filter( 'request', __NAMESPACE__ . '\request' );
```

???

**Comment by janboddez** [comment]
That would, I think, add the "RSS club" posts to way too many feeds. Like, if you had an unrelated CPT feed, it'd add the `rssclub` CPT to that.

But what I think you _could_ do is add it _everywhere you would normally expect `post`_.

Something like:
```
function request( $query_vars ) {
	if ( ! isset( $query_vars['feed'] ) ) {
		// Do nothing.
		return $query_vars;
	}

	if ( ! isset( $query_vars['post_type'] ) ) {
		// This is the *unaltered* main feed.
		$query_vars['post_type'] = array( 'post', 'rssclub' );
	} elseif( is_array( $query_vars['post_type'] ) && in_array( 'post', $query_vars['post_type'], true ) ) {
		// Wherever `post` is included, add `rssclub` as well.
		$query_vars['post_type'][] = 'rssclub';
	}

	return $query_vars;
}
add_filter( 'request', __NAMESPACE__ . '\request' );
```
(For IndieBlocks' notes, for instance, I don't want this, because I want to also provide "post-only" RSS feeds ... But in this case ... I think this would be fine.)

**Comment by janboddez** [comment]
I'm not sure if `$query_vars['post_type']` can also be a comma-separated string. If so, might also want to target that scenario.
